name: "Build / Test Presentation Code"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-presentations:
    name: "MARP Presentation"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: "Install Node"
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies and Puppeteer
        working-directory: ./presentation
        run: |
          npm ci
          sudo apt-get install libgbm-dev
          npm i puppeteer --no-save

      - name: Build Marp slide deck
        working-directory: ./presentation
        run: |
          CHROME_PATH=$(node -e "console.log(require('puppeteer').executablePath())") npm run build
          touch ./public/.nojekyll
        env:
          # Recommend to set lang for your deck to get better rendering for Open Graph image
          LANG: en-US
